---
Name: devtoolkit
After:
  - 'framework/*'
  - 'cms/*'
---
DefaultPasswordValidator:
  min_length: 6
  historical_passwords: 2
  characters:
    - 'digits'
AdminPasswordValidator:
  min_length: 10
  characters:
    - 'lowercase'
    - 'uppercase'
    - 'digits'
    - 'punctuation'
  characters_count: 3
# A smarter global partial key
SSViewer:
  global_key: '$CurrentReadingMode, $ContentLocale, $SiteConfig.ID'
ModelAdmin:
  extensions:
    - DevToolkitAdminExtension
SiteConfig:
  extensions:
    - DevToolkitSiteConfigExtension
Director:
  rules:
    'devtoolkitassets': 'DevToolkitAssetsController'
    'robots.txt': 'DevRobotsController'
    '__deploy': 'DeployController'
DeployController:
  # Replace with a secure key
  key: ''
  # Whitelisted servers
  ip_whitelist: []
LeftAndMain:
  extensions:
    - DevToolkitLeftAndMainExtension
DevToolkitAssetsController:
  enable_audit: true
  cms_access_ignore_rules: true
  admin_ignore_rules: true
  rules:
    'private': 'logged-in'
    'owner' : 'owner'
# ---
# Only:
#  classexists: 'FluentExtension'
# ---
# ContentController:
#  extensions:
#    - TranslatableActionsControllerExtension